version: '3.9'

services:
  beersapi:
    image: ot-beersapi
    build:
      context: .
      dockerfile: BeersApi/Dockerfile
    environment:
      zipkin__url: http://zipkin:9411/api/v2/spans
      pgsql__constr: Host=pgsql;Database=beersdb;Username=beersuser;Password=Passw0rd!
    ports:
    - 5100:80
    - 5101:443
    depends_on:
    - pgsql
    profiles:
      - api

  beers-seeder:
    image: ot-beers-seeder
    build:
      context: .
      dockerfile: Beers.Data.Seed/Dockerfile
    environment:
      pgsql__constr: Host=pgsql;Database=beersdb;Username=beersuser;Password=Passw0rd!
    profiles:
    - seed
    depends_on:
    - pgsql

  zipkin:
    image: openzipkin/zipkin-slim
    ports:
    - 9411:9411
    profiles:
      - api

  pgsql:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: beersuser
      POSTGRES_DB: beersdb

  adminer:
    image: adminer:4
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
      ADMINER_DEFAULT_DB_HOST: pgsql
      ADMINER_DEFAULT_DB_NAME: beersdb
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    profiles:
      - api
