apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
bases:
  - "../base"
patches:
  - path: cluster-role-patch.yaml
    target:
      kind: ClusterRole
      version: rbac.authorization.k8s.io/v1
      name: prometheus