apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy-pgsql.yaml
- svc-pgsql.yaml
namespace: hellomonitor
images:
- name: hellomonitor
  newName: dockercampusmvp/monitor-api
  # newName: Put your image name here
configMapGenerator:
  - envs:
    - pgsql.properties
    name: pgsql-cfg
    namespace: hellomonitor
