apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hellomonitor
  labels:
    monitor: "true"
spec:
  selector:
    matchLabels:
      app: hellomonitor
  endpoints:
  - port: web