apiVersion: batch/v1
kind: Job
metadata:
  name: helloapistress
spec:
  ttlSecondsAfterFinished: 1001
  completions: 20
  parallelism: 10
  template:
    spec:
      containers:
      - name: helloapistress
        image: peterevans/vegeta:6.9.1
        command:
        - "sh"
        - "-c"
        - "echo 'GET http://hellomonitor.hellomonitor/forecasts' | vegeta attack -rate=10 -duration=30s"
      restartPolicy: Never
