version: '3.9'

services:
  helloapi:
    image: monitor-api
    build:
      context: .
      dockerfile: HelloMonitor/Dockerfile
    environment:
      pgsql__constr: Host=pgsql;Database=hellodb;Username=hellouser;Password=Passw0rd!
    ports:
    - 5200:80
    - 5201:443
    depends_on:
    - pgsql
    profiles:
    - api

  hello-seeder:
    image: monitor-api
    environment:
      pgsql__constr: Host=pgsql;Database=hellodb;Username=hellouser;Password=Passw0rd!
    command: ["/seed"]
    depends_on:
    - pgsql
    profiles:  
    - seed

  pgsql:
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: Passw0rd!
      POSTGRES_USER: hellouser
      POSTGRES_DB: hellodb

  adminer:
    image: adminer:4
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: pgsql
      ADMINER_DEFAULT_DB_HOST: pgsql
      ADMINER_DEFAULT_DB_NAME: hellodb
      ADMINER_DEFAULT_DB_DRIVER: pgsql
    profiles:
    - api
