kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hellomonitor
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hellomonitor
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: http_requests_received
      target:
        type: AverageValue
        averageValue: 500m